Filter analysis_group by sample
dbmi-bgm/cgap-portal pull request #361
Opened 2021-03-12 18:17 UTC by alexkb0009

2021-03-13 21:33 UTC, sbreiff requested changes
I tested this a little on local, and its a big improvement, but there seems to a be a little bug still.

I uploaded a family that has a WES Trio analysis, a WGS Trio, and a WGS Quad analysis. 
The proband case for the WGS-Trio looks good: https://gyazo.com/65efe5c3debe5f6e9980ce81aa88320f
The proband case for the WGS-Group is missing the father's case, which had appeared correctly in the Trio case: https://gyazo.com/9ef0c93f8db4e68063b9e65d9992cd96

2021-03-15 18:23 UTC, sbreiff approved these changes
I tested this branch out again and the problem I described earlier was gone this time. I'm ok to merge (when tests pass I guess?) as it seems like a random issue, but will report if I see anything like this on prod in the future.

2021-03-15 19:06 UTC, Bianca-Morris approved these changes

2021-03-15 19:06 UTC, alexkb0009 commented on src/encoded/static/scss/encoded/modules/_tables.scss
> +					/* align-items: stretch; */ /* overrides default align-items: center */
Will remove this more fully later or adjust for different (.name) element to have align-self: stretch after testing more.

2021-03-15 19:08 UTC, Bianca-Morris commented on src/encoded/static/scss/encoded/modules/_tables.scss
> +					/* align-items: stretch; */ /* overrides default align-items: center */
Might make sense to get rid of these comments if we're not going to be using this, but it's not a super big deal. Especially if it's something that may be revisited/tweaked in future.

2021-03-15 19:09 UTC, Bianca-Morris commented on src/encoded/static/scss/encoded/modules/_tables.scss
> +					/* align-items: stretch; */ /* overrides default align-items: center */
Ha. You beat me to it.

2021-03-15 19:10 UTC, merged