PedigreeViz - wrap detail text
dbmi-bgm/cgap-portal pull request #403
Opened 2021-05-25 15:26 UTC by alexkb0009

2021-05-25 21:38 UTC, alexkb0009 commented on src/encoded/static/components/viz/PedigreeViz/IndividualsLayer.js
> +            { showAncestry.join(" • ") }
Wonder if better separator or formatting of some kind could be better here.. given that sometimes (depending on length+zoom level) it wraps to next to line.

2021-05-26 14:54 UTC, alexkb0009 commented on src/encoded/static/components/viz/PedigreeViz/IndividualsLayer.js
> +    const textContainerStyle = {
In future could maybe move some more of this into plain CSS..
This style object is essentially same for each such node so theoretically could be memoized at a higher level once and then passed down to all IndividualDiv > AboveNodeText.. 🤔

2021-05-26 16:00 UTC, alexkb0009 commented on src/encoded/static/components/viz/PedigreeViz/IndividualsLayer.js
> +    const textContainerStyle = {
..memoization part done

2021-06-02 18:42 UTC, Bianca-Morris requested changes
Looks like ancestry isn't showing up above the individual nodes anymore? And in the side-bar, the ancestry text is pretty jumbled together. https://gyazo.com/53f01add0c5e289dc045041bd58c0ac6

Phenotype overflow looks great, though.

2021-06-02 23:02 UTC, alexkb0009 commented
> Looks like ancestry isn't showing up above the individual nodes anymore? And in the side-bar, the ancestry text is pretty jumbled together. https://gyazo.com/53f01add0c5e289dc045041bd58c0ac6
> 
> Phenotype overflow looks great, though.

[Fixed the side-bar text](https://gyazo.com/7778b280856621cad85e19379943de35); for ancestry above nodes, it's only displayed for the terminal ancestors and not any child nodes (would overlap and/or prevent showing as much below-node detail text for nodes).

2021-06-08 21:33 UTC, merged