July 2021 feedback minor edits
dbmi-bgm/cgap-portal pull request #450
Opened 2021-08-04 22:49 UTC by alexkb0009

Contains a number of smaller edits from Trello ticket re: July 2021 feedback, and maybe 1 or 2 tangential fixes (i.e. getGene required a uuid which wasn't in the /embed request for one of the notes -- changed to just utilize `@id` for that and not embed uuid for any of the notes). There are a few more items in the ticket which didn't get to -- either due to lack of time or needing some more clarification -- and will put this PR into draft state if find time/clarity to work on them, otherwise this PR is ready for review.

It might make sense to go through each commit as each commit encapsulates an independent single or subset of features/changes.

2021-08-06 16:06 UTC, alexkb0009 commented on src/encoded/static/components/item-pages/CaseView/index.js
> +                <div className="card-body py-0">
BioInfoStats and BioInfoStatsEntry define their own padding now (`py-3` and `mt-04` + `mb-04`).

2021-08-06 16:08 UTC, alexkb0009 commented on src/encoded/static/components/item-pages/CaseView/index.js
> +                View <span className="text-600">Provenance Graph</span>
We don't have 'text-500' (or font-weight 500 in general) for the Source Sans webfont we're using (it renders as 400 instead) so adjusted such instances to 400 or 600 where made sense.

2021-08-06 16:14 UTC, alexkb0009 commented on src/encoded/static/components/browse/columnExtensionMap.js
> +            <h4 className="col-main" data-tip={titleTip} data-delay-show={titleTipDelayShow} data-html={tooltipEnableHtml}>
In current stylesheet-rules, there's 'text-truncate' styling applied to the `<span>` element here, so we need to have tooltip stuff on it or the column (as long as has the proper width (of column)) else tooltip will render in midpoint of (potentially-truncated) link if tooltip attributes applied to the mainTitle `<a href>` or whatever inline element, hence these props added to MultiLevelColumn.

(The `mainTitle` prop now tends to have a hyperlink element as its content/value)

2021-08-06 16:19 UTC, alexkb0009 commented on src/encoded/static/components/item-pages/VariantSampleView/InterpretationSpaceController.js
> -    getNote(uuid, noteType) {
Removed this method (and embedding of Note UUIDs in general for InterpretationSpace, which no longer needed as a result) altogether since can just be replaced by `ajax.promise(noteAtID + "?datastore=database", 'GET');` if using the `@id` instead of noteType+uuid.

2021-08-09 14:49 UTC, alexkb0009 commented on src/encoded/static/components/browse/columnExtensionMap.js
> +                    mainTitle={<a href={sampleId} className="adv-block-link">{ capitalizeSentence(specimen_type) }</a>} />
On 2nd thought, using CSS/`.text-capitalize` might've been better... but very negligible, will change possibly if have time.

2021-08-09 14:51 UTC, alexkb0009 commented on src/encoded/types/variant.py
> -    "variant_notes.note_text",
We're loading all the notes via /embed endpoint now so think we should be fine with this edit...

AnnotationSpace has all the embeds as most/all data is not on a linkTo, except maybe transcript.gene for currently-selected transcript.. but that is loaded via AJAX in UI.

2021-08-09 14:55 UTC, alexkb0009 commented on src/encoded/static/components/item-pages/VariantSampleView/VariantSampleOverview.js
> -                <InterpretationController {...passProps} interpretationTab={parseInt(interpretationTab) !== isNaN ? parseInt(interpretationTab): null} {...{ showInterpretation, caseSource, setIsSubmi
Might need to compare !== [NaN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN) but am unsure.. have usually used isNaN as func for safety in older browsers so am bit more comfortable w. that.

2021-08-09 19:24 UTC, Bianca-Morris requested changes
Code looks good aside from the one big problem with that import in `FilteringTab.js`.

I'm going to take a more thorough look at it on local, though, just to double check on the changes to note saving + a few other things.

2021-08-09 19:24 UTC, Bianca-Morris commented on src/encoded/static/components/item-pages/CaseView/FilteringTab.js
> +import { Alerts } from '../../../../../../../ext-projects/shared-portal-components/es/components/ui/Alerts';
This is causing a Module Not Found Error for me...
```
 ERROR in ./src/encoded/static/components/item-pages/CaseView/FilteringTab.js
    Module not found: Error: Can't resolve '../../../../../../../ext-projects/shared-portal-components/es/components/ui/Alerts' in '/Users/bmorris/projects/cgap-portal/src/encoded/static/components/item-pages/CaseView'
     @ ./src/encoded/static/components/item-pages/CaseView/FilteringTab.js 11:0-108 185:6-12
     @ ./src/encoded/static/components/item-pages/CaseView/index.js
     @ ./src/encoded/static/components/index.js
     @ ./src/encoded/static/libs/react-middleware.js
     @ ./src/encoded/static/server.js
```

Should it be `import { Alerts } from '@hms-dbmi-bgm/shared-portal-components/es/components/ui/Alerts';`?

2021-08-10 14:41 UTC, Bianca-Morris commented
One other comment: https://gyazo.com/6fa6a6282e9fe042a8d45e40f14e21b9 at this point it might make sense to just have the Patient Info, Family Info and Pedigree cards take up 1/3 of the window each. It's just a little off, which looks unintentional even if it's not necessarily. Since so many of the changes are cosmetic, it might make sense to deploy it somewhere and have Shannon & other folks look at it. (I'm also just having a hard time getting my inserts to cooperate with me so i can test notes)

2021-08-10 22:25 UTC, alexkb0009 commented on src/encoded/static/components/item-pages/CaseView/FilteringTab.js
> +import { Alerts } from '../../../../../../../ext-projects/shared-portal-components/es/components/ui/Alerts';
Yep, thanks!

2021-08-10 22:41 UTC, alexkb0009 commented on src/encoded/static/scss/encoded/modules/_item-pages.scss
> +    letter-spacing: 0.05em;
Hm yeah. Is fine in VS Code but there's also definitely not been good tabs-vs-spaces consistency in our SCSS files. It'd make sense to find/replace all tabs and convert to 4-spaces (or vice versa) (prly in sep. branch) (don't have much as to which; maybe 4-spaces since is used in rest of code).

2021-08-11 14:51 UTC, alexkb0009 commented on src/encoded/static/components/item-pages/CaseView/FilteringTab.js
> +            // todo add sentry.io call here.
Right now sentry is available on 4DN and theoretically can be initialized for CGAP (need to see what sentry project/id/config need to be used though). Going to see how is working for another week or so on 4DN (or until we have time to add it in) and then I think will (a) remove _most_ of the sentry calls from 4DN and (b) only add select/few sentry calls on CGAP where it makes sense to report an error -- will try to follow a soft convention of "would you want an email notification about this error? If yes, add sentry here; if not, then don't".

2021-08-11 14:51 UTC, merged