Exportable Spreadsheet Draft 1
dbmi-bgm/cgap-portal pull request #451
Opened 2021-08-09 19:05 UTC by alexkb0009

Ongoing

2021-08-09 19:08 UTC, sbreiff commented on src/encoded/types/variant.py
> +        impact_map = {
I don't think we need the impact map here. just the name. e.g. "missense variant"

2021-08-09 19:09 UTC, sbreiff commented on src/encoded/types/variant.py
> +    def get_most_severe_consequence(variant_sample_transcript):
the most severe consequence only applies for the most severe transcript. so it should not be called for the canonical transcript if csq_most_severe = False.

2021-08-09 19:16 UTC, sbreiff commented on src/encoded/types/variant.py
> +        return next(sorted(csq_consequences, key=lambda x: impact_map[x] ))
I'd write this function like this:

```
@lru_cache(maxsize=1)
    def get_most_severe_consequence(variant_sample):
        transcript = get_most_severe_transcript(variant_sample)
        csq_consequence = transcript.get("csq_consequence", [])
        return csq_consequence["display_title"]  # i don't know if you have frame=object here or what but you get the idea, hopefully
```

We might also need a similar one for the canonical consequence.

2021-08-10 22:48 UTC, alexkb0009 commented on src/encoded/static/components/item-pages/CaseView/AddToVariantSampleListButton.js
> +'use strict';
Nothing was changed in `AddToVariantSampleListButton` component aside from it being moved into its own file.

2021-08-10 22:50 UTC, alexkb0009 commented on src/encoded/static/components/item-pages/CaseView/SaveFilterSetButton.js
> +export class SaveFilterSetButtonController extends React.Component {
Nothing was changed in `AddToVariantSampleListButton` component aside from it being moved into its own file _and_ moving/defining `filterSetFieldsToKeepPrePatch` into this file and usage of it in place of (removed) `FilteringTableFilterSetUI.fieldsToKeepPrePatch`

2021-08-13 13:13 UTC, willronchetti reviewed
Letting out some minor style comments you can feel free to what you want with, will look at it again when marked ready

2021-08-13 13:13 UTC, willronchetti commented on src/encoded/batch_download.py
> +            if transcript.get("csq_canonical", False) == True:
When comparing booleans in Python, always use `is` rather than `==`.

2021-08-16 18:01 UTC, alexkb0009 commented on src/encoded/batch_download.py
> +        most_severe_impact_val = 100
Is just arbitrary, can replace with `Infinite` here I think.

2021-08-16 18:17 UTC, sbreiff commented on src/encoded/batch_download.py
> +        most_severe_impact_val = 100
I'm not sure this is necessary. I think this is already calculated, and the most severe consequence is just going to be the csq_consequence of the transcript where most_severe == true.

2021-08-16 18:44 UTC, alexkb0009 commented on src/encoded/batch_download.py
> +    ]
Was figuring if is a function it wouldn't keep living in memory when not needed but then again probably entirety of code is loaded into memory anyway so probably is moot.

2021-08-16 18:48 UTC, alexkb0009 commented on src/encoded/types/variant.py
> +        return next(sorted(csq_consequences, key=lambda x: impact_map[x] ))
`csq_consequence` is an array though and might have more >1 ?

2021-08-18 17:18 UTC, alexkb0009 commented on src/encoded/search/compound_search.py
> +    def es_results_generator(es_results):
Currently unused

2021-08-19 04:58 UTC, alexkb0009 commented on src/encoded/batch_download.py
> +            full_embedded_note = request.embed(incomplete_note_obj["@id"])
`incomplete_note_obj["@id"]` is always present from search response (regardless of permission) so we don't check if is present first. Could skip if `full_embedded_note["@id"]` is not present though, for permissions/security..

2021-08-19 05:04 UTC, alexkb0009 commented on src/encoded/batch_download.py
> +    del description_headers
If no variables left that reference the data, doesn't mean it'd get garbage-collected eventually?
(Lol is prly all moot since is just trying to shave off a few bytes for few seconds)

2021-09-20 16:04 UTC, Bianca-Morris approved these changes
Didn't look too closely at the python files (figure back-end folks would know best re: that stuff anyway), but the front-end updates look good and make sense.

One note; not necessarily blocking. I did try out some unicode symbols in notes, which don't convert to TSV or CSV accurately (which might be expected for CSV, not sure about TSV). I think I've seen in some places that they'll strip out those characters, but I doubt we'll see much use of them on CGAP for the time being so probably not importnat.. Ascii symbols seem to all work fine, however, so that's the majority of use cases covered. Good to be aware of this limitation for the future, though.

2021-09-21 13:39 UTC, sbreiff commented on src/encoded/batch_download.py
> +        suggested_filename = "variant-sample-filtering-" + timestamp + "." + file_format
Could we put the case ID/title into the suggested filename? Some of ours are long but maybe just the first 10 characters. Additionally, "variant-sample" is a term widely used by us in our data model but isn't necessarily intuitive to users ("sample variants" probably slightly moreso), so maybe instead just "variant-filtering" or just "filtering" after the case title.

2021-09-21 13:46 UTC, sbreiff commented on src/encoded/batch_download_utils.py
> +def build_xslx_spreadsheet(dictionaries_iterable, spreadsheet_mappings):
this should probably be "xlsx"

2021-09-21 15:20 UTC, alexkb0009 commented
Thx! I'll try out some unicode symbols on my local; I had utf-8 encoding defined on the endpoint(s) but that seemed to cause the unit test to not work (something internal to Pyramid TestApp, it seemed). If bring back the utf-8 encoding and it makes utf-8 characters be parsed appropriately, will look into more... maybe try to detect if running in test or not (and if not then add utf-8 encoding else no).

2021-09-21 15:35 UTC, willronchetti requested changes
Tests will not pass in current state due to workbook changes. Also, we should consider if this operation scales well enough to just be a route (and not an ingestion job).

2021-09-21 15:35 UTC, willronchetti commented on src/encoded/search/compound_search.py
> +    @staticmethod
What are you trying to accomplish with this change? You've done it in several places and it isn't obvious to me what benefit it has.

2021-09-21 15:35 UTC, willronchetti commented on src/encoded/search/compound_search.py
> +    @staticmethod
Same deal here - why?

2021-09-21 15:35 UTC, willronchetti commented on src/encoded/tests/data/workbook-inserts/variant.json
> +    {
Additions here break all the search tests, yes?

2021-09-21 15:37 UTC, sbreiff commented on src/encoded/types/variant.py
> +    "interpretations.@id",
I thought @id was always embedded when other subproperties are embedded

2021-09-21 19:37 UTC, sbreiff commented on src/encoded/types/variant.py
> +            if pop_val is not None and pop_val == csq_gnomadg_af_popmax:
in places like this you could use `if pop_val` instead of `if pop_val is not None` - if pop_val were 0, that's not None, but its still not a value we'd want to consider as the max.

2021-09-24 15:08 UTC, alexkb0009 commented on src/encoded/search/compound_search.py
> +    @staticmethod
Clarity for self; in my mental convention, classmethods usually return class instances and static methods are static methods. So changed a couple of those around but then stopped because didn't want to start renaming `cls` too much.

2021-09-24 15:13 UTC, alexkb0009 commented on src/encoded/batch_download.py
> +            yield embedded_representation_variant_sample
It 'feels' like it works very fast even for ~7k variant samples on the _FilteringTab_ (tested on cgaptest). The download stream starts immediately so to end-user it looks like file is immediately available and then is just downloading for however long it takes. At this point it might take some 10-20s+ for that many VSes but it just looks like a file being downloaded and isn't affected by 30sec timeout limit(s) -- and since is getting most of data from ElasticSearch it finishes relatively fast in general.

My main concern is the _InterpretationTab_ which makes datastore=database requests via embed endpoint, and it takes much longer (per VariantSample) to download (around ~2kb/sec is what end-user sees would see). If only 10 or so VariantSamples then isn't big deal, but if more it may become a problem IMO... but probably tolerable still since is file download in background (relatively) and not an AJAX request that's holding up the UI..

2021-09-24 15:15 UTC, alexkb0009 commented on src/encoded/types/variant.py
> +    "interpretations.@id",
True.. though explicitness isn't a bad thing IMO. (In this case we definitely need the `@id`, idk).

2021-09-24 15:18 UTC, alexkb0009 commented on src/encoded/search/compound_search.py
> +    @staticmethod
Was thinking we could change it to a 'module[/file] of functions' (since no class logic really being used/needed) also and get rid of boilerplate class stuff but probably not worth the effort.

2021-09-24 16:31 UTC, alexkb0009 commented
I made a couple of edits and will still make some edits to e.g. filename, but am stuck with the tests. Not sure how to get them to work with new workbook-inserts. On GA getting some SSL timeout errors (but not on local), on local getting some "/index not found" errors (doesn't seem related?), and also these [2 seemingly-related failures](https://gyazo.com/8637fedc2aef52971eba7c4f428b2740)... but also no idea how to address it to get them to work..

2021-09-29 17:19 UTC, alexkb0009 commented
@Bianca-Morris I tested UTF-8 chars and the MacOS "Numbers" app displayed them correctly automatically while Excel did not. Upon looking into it a bit more, I think Excel [by default doesn't parse CSVs as UTF-8 unless "Import" it with specific options](https://answers.microsoft.com/en-us/msoffice/forum/all/how-to-open-utf-8-csv-file-in-excel-without-mis/1eb15700-d235-441e-8b99-db10fafff3c2). Looking into if can trigger it to parse at UTF-8 automatically without much complexity, else probably leave as-is (not much UTF-8 stuff I think anyway..).

Will try to push headers/summary stuff today and merge asap.

2021-09-29 19:05 UTC, alexkb0009 commented
Will merge once local tests pass (or GA, if doesnt time out)

2021-09-30 00:05 UTC, merged