Refactor Nested Query Building
dbmi-bgm/cgap-portal pull request #454
Opened 2021-08-11 17:54 UTC by willronchetti

- Refactors the core query building functionality for nested queries so that it correctly handles multiple selections with AND instead of OR
- TODO: add more tests

2021-08-11 18:03 UTC, netsettler commented on src/encoded/tests/test_search.py
> +        assert 'f6aef055-4c88-4a3e-a306-d37a71535d8b' in uuids
A comment here, at minimum, would be helpful. Arguably I'd like to see
```
SOME_NICE_NAME = 'f6aef055-4c88-4a3e-a306-d37a71535d8b'  # optional description if name isn't nice enough
SOME_OTHER_NICE_NAME = ... # also described
...
    assert SOME_NICE_NAME in uuids
    assert SOME_OTHER_NICE_NAME in uuids
```

2021-08-11 18:06 UTC, netsettler commented on src/encoded/tests/test_search.py
> +                       '&POS=11720331&hg19.hg19_pos=11720331', status=404)
This change is different in nature than the others. I assume it's intended. But I"m just flagging it for you to look at a second time since I'm not competent to give it the additional scrutiny it needs.

2021-08-15 21:33 UTC, drio18 requested changes
I believe you were correct in your caution surround lines 509-512 in `handle_nested_filters_v2`. There's some funky stuff going on there concerning the object type (list or dict) of the query being built, and as the code currently stands nested searches are not functioning correctly in a few important cases that need to be addressed (see comments). I could not identify a quick fix here after some poking around, but I tried to understand the issue and clarify what problems were occurring as far as I could tell.

One other area to address is nested searches greater than one level deep. I didn't play around with this issue, but once the search for nested terms appears to be working it'd be good to test a second-level type search at minimum.

2021-08-15 21:33 UTC, drio18 commented on src/encoded/search/lucene_builder.py
> +                    nested_query[BOOL][key].append(cls.build_nested_query(nested_path, query))
This comment is out of order and follows on the comments below, but I believe this is where the trouble is being introduced with respect to the nested query being built as a list when starting with an `exists` type query. Consider checking to see if the `query` is a list as you do in lines 482-498 above for `_sub_query`. You may have to introduce a similar check for lists at line 472, though I'm less confident of that. 
```suggestion
                    if isinstance(query, list):
                        query = query[0]
                    nested_query[BOOL][key].append(cls.build_nested_query(nested_path, query))
```

2021-08-18 21:34 UTC, drio18 approved these changes
Looks great and is much cleaner/slicker than the previous version (the one currently in prod). I think a little logic can be further condensed, but most of my other comments are minor. It may be nice to have the workbook built out more for testing "deeper" nesting, but you know much more about how these are handled than I do, so perhaps not a big issue.

2021-08-18 21:34 UTC, drio18 commented on src/encoded/tests/test_search.py
>              ]
Consider deleting this search as doesn't fall under this test name and is duplicated more appropriately in lines 896-898 (though without checking the uuids there).

2021-08-23 15:24 UTC, willronchetti commented on deploy/docker/local/docker_development.ini
> +load_test_data = encoded.loadxl:load_deploy_data
A change from Doug's branch needed to trigger deploy data loading in new environments.

2021-08-23 15:24 UTC, willronchetti commented on poetry.lock
> +version = "1.17.108"
Yeah I think I just ran `poetry update` at some point. Can revert and keep master version if needed.

2021-08-23 15:25 UTC, willronchetti commented on deploy/docker/production/nginx.conf
> +        keepalive 32;
A superstitious change that I think may help things in the ECS setup: https://nginx.org/en/docs/http/ngx_http_upstream_module.html?#keepalive

2021-08-23 16:56 UTC, netsettler commented on src/encoded/search/lucene_builder.py
> +            filters_to_work_on += zip([MUST] * len(must_nested_filters), must_nested_filters)
Seems like there should be a `distribute` function that does this (untested):
```
def distribute(item, seq):
    return zip([item]*len(seq), seq)
```
then later
```
    filters_to_work_on += distribute(MUST, must_nested_filters)
```
or something like that. Anyway, this is fine, just interrupted by visual clutter or low-level Python cuteness.

2021-08-23 16:56 UTC, netsettler commented on src/encoded/search/lucene_builder.py
> +                        combined_query[BOOL][MUST].append(sub_query)
I might be confused, because I confess I don't totally follow this, but should this be a `MUST_NOT`?

2021-08-23 17:14 UTC, netsettler approved these changes
I did not review the algorithm since it looks like Doug already did. Unit tests would have helped a lot that just illustrate some of the tree surgery being done. But I see nothing blocking this going ahead unless you want a more detailed algorithmic review, in which case the best thing to do is make time with me and work through it a little interactively.

2021-08-23 17:14 UTC, netsettler commented on src/encoded/search/lucene_builder.py
> +    @staticmethod
Are there unit tests for this? I don't see any added or changed for this specific function, and yet this looks like the kind of function that could have useful unit tests that would make its operation clearer.

2021-08-23 20:59 UTC, merged