FilterSet/FilterBlocks - Save FilterBlocks for VS selection
dbmi-bgm/cgap-portal pull request #544
Opened 2022-01-18 22:56 UTC by alexkb0009

Should be relatively self-explanatory in code/schema-edits.

We now save new field VariantSampleList.variant_samples.filter_blocks_used (and for structural_variant_samples) into which we put in FilterBlocks used (name and query) to find that VariantSample, whether 1 or many. Plus if intersection was used or not (`filter_blocks_used: { intersection: boolean, filter_blocks: { name: string, query: string }[] }`).

Case FilterSet FilterBlocks are validated against the already-saved filter_blocks_used, and using same name with a different-than-already-saved-value is invalid. This will be indicated in the UI, with "Add to Interpretation" button disabled until this is corrected.

![](https://i.gyazo.com/a54885dc9825de60d2ce63cebd5d6d27.png)

----

#### Potential Issues

- We still have the old field `filter_blocks_request_at_time_of_selection`. It however mostly has incorrect info (i.e. no filter blocks saved if all were selected) and is probably just worth deleting it and its valued (currently preserved in this PR, but marked as deprecated). Not sure on quickest way to accomplish this, probably just some PATCHes (vs an upgrader) and then delete field from schema in later commit/PR?

----

#### Readiness

This PR is mostly ready for review. Am adding minor touchups now but nothing should drastically change.

2022-01-19 20:24 UTC, Bianca-Morris requested changes
Noticed some errors. I added a suggestion for how to the big one, but the other few I didn't know how to fix off of the top of my head, so I left some info on what I'm seeing.

2022-01-19 20:24 UTC, Bianca-Morris commented on src/encoded/static/components/item-pages/CaseView/FilteringTableFilterSetUI/AddToVariantSampleListButton.js
Something in here is broken; if I had to guess I'd say somewhere between lines 104 and 135, but can't really be sure. I'm getting two different errors for SNVs and CNVs when I try to move variants to interpretation. For SNVs, it looks like [this](https://gyazo.com/2ec1611404cab774bb3cda8fe491a5c9). For CNVs, it's [this](https://gyazo.com/a0c58182cbb7c55ee14af2147e614a9d).

2022-01-20 15:48 UTC, drio18 requested changes
I tried playing around on dev but was unable to add SVs to a VSL (infinitely looping circle for "Saving selections"). Leaving some comments/questions regarding data model/permissions and will happily test more anytime.

2022-01-20 17:07 UTC, alexkb0009 commented on src/encoded/search/compound_search.py
> +            setting status on the request if needed. Also sets "__matching_filter_block_names" computed field to identify
It's generated by compound_search endpoint when multiple requests/queries/filter-blocks are sent to it. It's backend-search-generated for any/all Item types, but only in compound search, so definitely not a standard field name as others (unlike calculated properties, etc.).. so figured this would be an OK way to differentiate it for now. We added this in recently but changed name to "names" here to be more correct (we send indices as names from UI as aligns easily w. existing 'selectedIndices' state but any filter block name would work, depending on use case).

2022-01-20 17:08 UTC, alexkb0009 commented on src/encoded/static/components/item-pages/CaseView/FilteringTableFilterSetUI/AddToVariantSampleListButton.js
1st error is glitch which fixed re: permissions (needed to enable role.owner in base.py local roles method). For 2nd one.. might need to reboot make deploy2 (app server) for new name to take effect; if that doesn't work I'll look into more.

2022-01-20 17:59 UTC, alexkb0009 commented on src/encoded/static/components/item-pages/CaseView/FilteringTableFilterSetUI/AddToVariantSampleListButton.js
Ah ok I got 2nd 1, looking into..

2022-01-20 18:13 UTC, alexkb0009 commented on src/encoded/static/components/item-pages/CaseView/FilteringTableFilterSetUI/AddToVariantSampleListButton.js
Issue was when only 1 filter block exists on local state, it would always also be 0 selected indices (which === 'all selected'). Added touchup/fix for this.

2022-01-20 18:35 UTC, alexkb0009 commented on src/encoded/types/base.py
> +    (Allow, 'role.owner', ['view', 'view_details', 'edit']),
Not sure on view_details, saw it in user.py so decided to replicate. Removed for now (seems to work still).

2022-01-20 18:36 UTC, alexkb0009 commented on src/encoded/tests/data/workbook-inserts/variant_sample_list.json
>                  "userid": "834559db-a3f6-462c-81a4-f5d7e5e65707",
Good catch, thanks!

2022-01-21 14:53 UTC, Bianca-Morris approved these changes
Edits look good, I slacked you with a couple of ui/ux questions, but if that's all intended functionality this should be good to merge. Going to rerequest from doug too, so he can double check that his concerns have also been addressed.

2022-01-21 16:27 UTC, drio18 commented on src/encoded/schemas/variant_sample_list.json
> -                                    "additionalProperties": true,
You'll want to set this to be an explicit `false` as the default value is `true`. Same for `structural_variant_samples` below.

2022-01-21 16:27 UTC, drio18 commented on src/encoded/tests/test_upgrade_variant_sample.py
> +    assert "filter_blocks_request_at_time_of_selection" not in vsl_to_upgrade
This test, while passing, is going to pass regardless of whether the upgrader did its job, as `"filter_blocks_request_at_time_of_selection"` is never a high level property on the item. You'll want to test that it's removed from the items in the `variant_samples`, e.g.:
```suggestion
    variant_samples = vsl_to_upgrade.get("variant_samples")
    assert len(variant_samples) == 2
    for variant_sample in variant_samples:
         assert "filter_blocks_request_at_time_of_selection" not in vsl_to_upgrade
```

2022-01-21 16:27 UTC, drio18 commented on src/encoded/upgrade/variant_sample.py
> +
Just conventional style: these 2 lines plus the empty lines below the docstring and at the end of the file can be deleted.

2022-01-21 16:27 UTC, drio18 commented on src/encoded/static/components/item-pages/CaseView/FilteringTableFilterSetUI/AddToVariantSampleListButton.js
> +                <span data-tip="Check for any errors above such as duplicate filter block name or changing contents of a filter block that's been used to add a sample already. Otherwise, check user p
Typo within the data-tip, and consider style changes:
```suggestion
                <span data-tip="Check for any errors above such as a duplicate filter block name or a change to the contents of a filter block that has been used to add a sample already. Otherwise, check user permissions.">
```

2022-01-21 17:23 UTC, merged