DRAFT: Reduce Case embeds + UI edits
dbmi-bgm/cgap-portal pull request #553
Opened 2022-01-28 23:26 UTC by alexkb0009

So far the UI edits have been to migrate away from `Case.family` and `Case.secondary_families` to `Case.sample_processing.families` -
- `Case.family` will be kept, but only UUID kept, in order to select `canonicalFamily` (with all needed embeds) from `Case.sample_processing.families`.
- `Case.secondary_families` will be removed completely (**needs confirmation**). In place of it, memoized call of `Case.sample_processing.families.filter(function(family){ return family !== canonicalFamily; })` is used.

### Important Remaining to-dos
- Figure out and move embeds around in Case.embedded_list on backend.
- Find/test a Case with multiple families.
- Change the base of this branch to 'master' instead of `touchups-ui-2022-01c`, once the latter is merged.

2022-02-04 20:29 UTC, alexkb0009 commented on src/encoded/types/case.py
> +        *_build_family_embeds(base_path='sample_processing.families'),
Leading "*" is python spread operator, used it for readability (not have to split up list into multiple ones).

2022-02-04 20:30 UTC, alexkb0009 commented on src/encoded/types/case.py
> +        *_build_family_embeds(base_path='sample_processing.families'),
Things which were defined below for "sample_processing.families" but not present in `_build_family_embeds` were added into _build_family_embeds. Might be able to trim _build_family_embeds down a tiny bit later.

2022-02-08 19:13 UTC, Bianca-Morris requested changes
After a lot of testing, I don't think this is ready for a merge. There are quite a few bugs with the pedigree visualization and cases. Here's a breakdown of what I found and what cases they were associated with:

- Broken pedigree lines for certain cases:
  - http://fourfront-cgaptest.9wzadzju3p.us-east-1.elasticbeanstalk.com/cases/GAPCAN3NPFYZ/
  - [![Image from Gyazo](https://i.gyazo.com/4bab6291eb570c7cf386adeb8d0f62bc.png)](https://gyazo.com/4bab6291eb570c7cf386adeb8d0f62bc)
- Load errors on other cases, like this one:
  - http://fourfront-cgaptest.9wzadzju3p.us-east-1.elasticbeanstalk.com/cases/GAPCA1A5BQB3/
  - [![Image from Gyazo](https://i.gyazo.com/1ab3f6c68171ff13af7dc26573405a2b.png)](https://gyazo.com/1ab3f6c68171ff13af7dc26573405a2b)
- And this one:
  - http://fourfront-cgaptest.9wzadzju3p.us-east-1.elasticbeanstalk.com/cases/GAPCA1A5BQB3/
  - [![Image from Gyazo](https://i.gyazo.com/2234ea85f50cc7aabed04f2d7b6d88d3.png)](https://gyazo.com/2234ea85f50cc7aabed04f2d7b6d88d3)

2022-02-22 17:08 UTC, alexkb0009 commented
Went through cgap-devtest and seems OK now. But haven't been able to replicate the FileDownloadButton exception yet...

2022-02-22 18:09 UTC, willronchetti approved these changes
Looks great, seems to further improve case search performance on devtest

2022-02-22 19:41 UTC, Bianca-Morris approved these changes
Looks like the issues I ran into last time have been resolved. Seems good to go!

2022-02-22 21:10 UTC, merged