Technical Review on Filtering Tab
dbmi-bgm/cgap-portal pull request #595
Opened 2022-05-03 23:04 UTC by alexkb0009

Requires a SPC release + version update (1-liner, already in SPC master).

2022-05-03 23:07 UTC, alexkb0009 commented on src/encoded/schemas/structural_variant_sample.json
> +                    "permission": "restricted_fields"
Only admins will be allowed to manually edit this field (and initial_call_made_by), otherwise will be populated by server. This should be fine as when new call is made, these fields are completely removed.... but will need to double check & test with normal user permissions. Assuming it does work fine, want to keep "reviewed" date/by and probably technical notes in separate field(s), like "technical_review_notes", whether is linkTo note or text field.. in part to avoid permissions from PATCHing technical_review which has admin-only-editable initial_call_made fields.

2022-05-06 15:39 UTC, drio18 reviewed
Leaving some comments regarding the data model. One of them (not wrapping under parent property) would likely require some work to refactor the PR, but I think it's the right move unless there are other strong reasons against doing so.

2022-05-06 15:39 UTC, drio18 commented on src/encoded/schemas/structural_variant_sample.json
> +        "technical_review": {
Since this property is identical to that in VariantSample, can we make it a mixin instead to simplify future maintenance?

Also, more importantly, why is this an object instead of being separate properties? The latter is preferable for ES reasons, I believe, so there should be a strong rationale for wrapping everything under a parent property. We generally try to use objects when we need an array of objects; otherwise separate properties should do the trick.

2022-05-06 15:39 UTC, drio18 commented on src/encoded/schemas/structural_variant_sample.json
> +                    "description": "True if call, false if no call, or undefined"
Can we clarify this comment to make it sound less as though there are 3 options? Also, what exactly is a "no call"; I don't entirely get this terminology.
```suggestion
                    "description": "True if call, false if no call or undefined"
```

2022-05-06 15:39 UTC, drio18 commented on src/encoded/custom_embed.py
> +            "The following IDs were invalid: %s" % ", ".join(invalid_ids)
This is a curious inclusion in this PR. What was the issue?

2022-05-06 16:13 UTC, alexkb0009 commented on src/encoded/schemas/structural_variant_sample.json
> +        "technical_review": {
I'm not sure there's much of an issue with having it an object vs separate properties. I think issue for ES is for many embedded linkTo items? Having an object makes it possible to have the backend-generated "date_initial_call_made" and "initial_call_made_by" fields. Otherwise those backend-generated fields can't be separate fields without like a special backend endpoint that accepts "technical_review_classification" and "technical_review_call" and then populates "date_initial_call_made" + "initial_call_made_by".

2022-05-06 16:14 UTC, alexkb0009 commented on src/encoded/schemas/structural_variant_sample.json
> +                    "description": "True if call, false if no call, or undefined"
No Call as in [this](https://gyazo.com/4232a63bade9ffff8b591c2fd7bc3156). A value of `False` in this case is separate from if it was undefined or not present (no value).

2022-05-06 16:16 UTC, alexkb0009 commented on src/encoded/custom_embed.py
> +            "The following IDs were invalid: %s" % ", ".join(invalid_ids)
Heh, I spent like few minutes trying to figure out where there was a typo in an ID that had "." appended to it (looking thru inserts etc), before realizing it came from the log stmt. Not really important though.

2022-05-06 16:23 UTC, alexkb0009 commented on src/encoded/schemas/structural_variant_sample.json
> +        "technical_review": {
Good call re: mixin

2022-05-06 17:54 UTC, Bianca-Morris approved these changes
Looks good to me. Can you remind me of the plan for addressing the column getting reset after saving the new technical review states? That's the one thing UX wise that I see being an issue in the short-term.

2022-05-06 17:54 UTC, Bianca-Morris commented on src/encoded/static/components/item-pages/CaseView/TechnicalReviewColumn.js
> +    const handleOpenDropdownCall = useCallback(function handleOpenDropdownCall(){
Out of curiosity, is there a reason why you're declaring a named function inside of the useCallback here instead of an anonymous one?

2022-05-06 18:00 UTC, drio18 reviewed
Few more comments based on updates and playing around on devtest. I wasn't able to impersonate non-admins on devtest so couldn't test permissions, though I don't think that'd be an issue here.

See my comments on the date and made by properties for my biggest concern about having a revision history here.

2022-05-06 18:00 UTC, drio18 commented on src/encoded/schemas/mixins.json
> +                    "description": "Descriptor for the call or no call",
Consider
```suggestion
                    "description": "Reason for the given call choice",
```

2022-05-06 18:00 UTC, drio18 commented on src/encoded/schemas/mixins.json
> +                }
If I understand your previous comment correctly, I suppose it makes sense to keep this an object if that's the best way to have the server autopopulate these fields. It's generally not desirable to have objects because, as I understand it, sub-embedded properties of an object have to be further "mapped out" on the ES documents, increasing their size, though I'd need to check with Will. It's likely a larger issue for arrays of objects, since they'd all have to mapped out. It's definitely not as big of a deal as embedded linkTos, but I generally try to avoid objects when simple properties will do. I agree it makes sense here now.

2022-05-06 18:00 UTC, drio18 commented on src/encoded/schemas/structural_variant_sample.json
> +                    "title": "Initial Call Made Date"
These sorts, while they seem like they should work well, don't really help at all. Sorting in either direction on any of the fields here doesn't pull variants "to the top" from playing around on devtest. Perhaps these can't be sorted correctly? No idea.

2022-05-06 18:00 UTC, drio18 commented on src/encoded/schemas/mixins.json
> +                "initial_call_made_by": {
Can we remove the "initial" portion of these fields? They're overwritten whenever someone changes the call, making the naming confusing here. 

Also, my guess is users would want to know if/when the call has been changed as well based on Kalotina's feedback yesterday; may be worth confirming with Dana/users. If we need to keep revision history on these items, may be worth it to make new item types for technical review that are linkedTo by the VariantSample. Don't know if it's difficult to obtain revision history for a specific field on an item.

2022-05-06 19:35 UTC, alexkb0009 commented on src/encoded/static/components/item-pages/CaseView/TechnicalReviewColumn.js
> +    const handleOpenDropdownCall = useCallback(function handleOpenDropdownCall(){
> Looks good to me. Can you remind me of the plan for addressing the column getting reset after saving the new technical review states? That's the one thing UX wise that I see being an issue in the short-term.

No real plan at moment. Eventually we need new infrastructure, such as a Redis PubSub server, and server-sent-events API endpoint, to allow us to send notifications/events to online clients to inform them to update their search or something (or maybe individual search results, if we setup a mechanism for that).

> Out of curiosity, is there a reason why you're declaring a named function inside of the useCallback here instead of an anonymous one?

Nope, just forgot to remove name when changed it to a useCallback.

2022-05-06 19:40 UTC, alexkb0009 commented on src/encoded/schemas/structural_variant_sample.json
> +                    "title": "Initial Call Made Date"
Hm it [seems to work for me](https://gyazo.com/a15930b7177f426634a5d76c87a00eef) on local...

2022-05-06 19:42 UTC, alexkb0009 commented on src/encoded/schemas/mixins.json
> +                "initial_call_made_by": {
Will think about this a bit more.. thinking if needed, can create NoteTechnicalReview Item and add call and classification as properties on that, but then would need to rework most of this branch... hoping we can maybe rely on revision history of the VariantSample potentially... hmm.. idk

2022-05-06 19:50 UTC, alexkb0009 commented on src/encoded/schemas/mixins.json
> +                "initial_call_made_by": {
Yeah the PostgreSQL database keeps revision per item. It's a little annoying to get revisions for just 1 field since basically need to compare each 'version' to see if that field changed in that version and then filter all versions down to ones where those fields were affected.. but doable with effort..

2022-05-06 19:51 UTC, alexkb0009 commented on src/encoded/schemas/mixins.json
> +                "initial_call_made_by": {
Topic for different discussion -- this takes up a lot of memory in PostgreSQL, I think we could make it so that each "transaction" (PATCH payload essentially) is stored in the database, and then create a calculated database view of an 'current' Item as the sum of all those transactions since Item been created... but guessing we won't be able to do this for a while.

2022-05-13 16:43 UTC, alexkb0009 commented on src/encoded/types/variant.py
> +    # We need the following data in search result rows, so we embed these here and not thru /embed API.
Once get further along with implementation, and if makes sense for performance/ease-of-UI-code-implementation, maybe will remove embeds to Notes, and then AJAX them in only when click on Note icon in search result...

2022-05-25 14:29 UTC, alexkb0009 commented on src/encoded/types/variant.py
>      context=VariantSample,
I guess this should apply to StructuralVariantSamples too.. unsure simplest way, import `process_items` from this file into structural_variant.py and wrap with SV-specific endpoint?

2022-06-28 15:49 UTC, Bianca-Morris reviewed
This seems to be working for me. I'll leave it to @shannonehmsen to determine whether overall UX is right. I did notice a few small things that could be better, though:

- Sometimes the technical review note dropdown pushes down the edge of the page; I'm not sure what the cause is, since it's not every single time, but could be worth looking into. 
[![Image from Gyazo](https://i.gyazo.com/cdf487a87ba5fe84914f72e1989a9ae2.png)](https://gyazo.com/cdf487a87ba5fe84914f72e1989a9ae2)

- Only some notes created by admins are visible for non-admins. These are the same variants as in the above image, but none of them show up for Joel. Might be expected behavior for users from different projects, but not sure.
[![Image from Gyazo](https://i.gyazo.com/019115aa4f0005025eea7deab854b5be.png)](https://gyazo.com/019115aa4f0005025eea7deab854b5be)
It does look like they aren't able to overwrite a note, though, which is good:
[![Image from Gyazo](https://i.gyazo.com/0b4088bfc61bfbf123266770528259e7.png)](https://gyazo.com/0b4088bfc61bfbf123266770528259e7)

- When the popovers are open, scrolling the parent container causes them to reposition to the top left of the page.
[![Image from Gyazo](https://i.gyazo.com/c013b70cb7f41fdad52d8e4b70defd31.gif)](https://gyazo.com/c013b70cb7f41fdad52d8e4b70defd31)

I still haven't tested the Recurring Artifact 'save to all projects' thing thoroughly because I'm not entirely sure what the outcome of that is meant to be. Is the idea that that one variant will have a note applied across all cases in the project? Is there a set of cases on devtest that could be used for testing this?

2022-06-29 15:35 UTC, drio18 requested changes
Data model looks good. Leaving many comments, some are stylistic with which you can do as you please but others require clarification/changes. I think the process notes endpoint could use some serious refactoring and unit testing to make it more manageable, as right now only a few integrated tests are present. Also, if you're not using a linter for the python code as you go, please use a code formatter once finished to clean up a lot of the formatting details (I use and prefer black, but any should do).

I haven't tested the functionality on devtest much at all, so will be doing that shortly and then may drop more comments if needed.

2022-06-29 15:35 UTC, drio18 commented on src/encoded/types/variant.py
> +        variant_fields_needed.append("technical_reviews.project")
Consider refactoring; a lot of redundancy here can be handled more simply to make it easier to add new items if they come along.

2022-06-29 15:35 UTC, drio18 commented on src/encoded/types/variant.py
> +def process_items_process(context, request):
Also, consider adding in a variant field name kwarg to eliminate the multiple times below the difference between VariantSamples and StructuralVariantSamples is handled.

2022-06-29 15:35 UTC, drio18 commented on src/encoded/types/variant.py
> +def process_items_process(context, request):
Consider significantly refactoring this function for maintenance/testing purposes. All the nested functions should probably be moved out to independent functions for testing/mocking at least. There are a few areas where additional helper functions would also be useful for simplifying some redundancy and testing.

2022-06-29 15:35 UTC, drio18 commented on src/encoded/types/variant.py
> +        add_or_replace_note_for_project_on_variant_or_gene_item("technical_review", variant, variant_patch_payload, remove=True)
A lot of redundancy here as well than can likely be simplified via helper functions +/- other refactoring.

2022-06-29 15:35 UTC, drio18 commented on src/encoded/tests/test_indexing.py
> +        )
This test is failing as is.

2022-06-29 15:35 UTC, drio18 commented on src/encoded/schemas/note_technical_review.json
> +    "properties": {
Need a schema version field here
```suggestion
    "properties": {
           "schema_version": {
                 "default": "1"
            },
```

2022-06-29 15:35 UTC, drio18 commented on src/encoded/server_defaults.py
> +def userinstitution(instance, subschema):
Would be good to add unit tests for this and the above.

2022-06-29 15:35 UTC, drio18 commented on src/encoded/types/variant.py
> +    default_diff = ["variant.technicals_reviews"]
Where/how is this being used?

2022-06-29 17:15 UTC, alexkb0009 commented on src/encoded/schemas/variant_sample.json
> +        },
(Resolved -- need to remap updated schema on devtest)

2022-06-29 17:27 UTC, alexkb0009 commented on src/encoded/server_defaults.py
> +    user = request.registry[COLLECTIONS]['user'][userid_found]
I agree in principle but this actually increases the # of [lines of code by 3](https://gyazo.com/e54e25585e76e9a5d0e1f6db63428783) ... so unsure if best thing to do here.

2022-06-29 17:32 UTC, alexkb0009 commented on src/encoded/search/search.py
> +            del subreq.environ['HTTP_COOKIE']
Eh only if they hack the system are able to get it to execute arbitrary code. `get_iterable_search_results` is only called/used by app-internal functions like code for exporting spreadsheet and here so there should be no way for users to call it directly.

2022-06-29 17:37 UTC, drio18 commented on src/encoded/schemas/note_technical_review.json
> +    "properties": {
No, the mixin doesn't create a default version, and it's required to add the default in to each schema or else issues with upgrading can occur. Will and I made some recent snovault fixes to patch the upgrader bug, so it shouldn't occur in the future, but still best practice is to add the default version to each item schema. There's also a test now that would have failed and caught this to try and enforce the practice. We thought about making the mixin have a default version, but there were some issues with doing so.

2022-06-29 17:39 UTC, alexkb0009 commented on src/encoded/types/note.py
> +            pass
That was the first thing I tried but it throws an AttributeError/KeyError with message of `""` when do this. `try...catch` approach was the only solution that worked here. As I understand it's something in Pyramid's internal code (I think it throws not-fully-standard type/args of Exception or something).

2022-06-29 17:41 UTC, alexkb0009 commented on src/encoded/types/note.py
> +
Whitespace to help organize/separate things is a good thing IMO, especially if try to follow some conventions (like 4 spaces between classes, 1 spaces between methods within a class, 2 spaces between a class and function(s) related to that class; something like that), but will remove a couple.

2022-06-29 17:53 UTC, drio18 commented on src/encoded/types/note.py
> +
Yeah, python conventions indicate 2 spaces between classes: https://peps.python.org/pep-0008/#blank-lines.

2022-06-29 17:59 UTC, alexkb0009 commented on src/encoded/types/variant.py
> +    default_diff = ["variant.technicals_reviews"]
I'm not sure, I think Will asked me to put it in while debugging invalidation scope or smth, will remove.

2022-06-29 18:02 UTC, alexkb0009 commented on src/encoded/types/variant.py
> +def process_items_process(context, request):
I agree, I just don't know best place to put this. Will leave for Kent/Willl/you to refactor as see best.

2022-06-29 18:04 UTC, drio18 commented on src/encoded/types/variant.py
>          raise HTTPServerError("Couldn't update Item " + item_atid)
So should it be an OR rather than an AND? I'm confused why both would need to fail in order to raise the error.

2022-06-29 18:34 UTC, drio18 reviewed
Leaving some comments related to UI/UX after playing around on devtest:

- The permissions issue Bianca mentioned is worth thinking about more. If multiple projects have permission to view the case/variants, should they able to see and/or edit each others' notes? Should we not allow someone to make a note if someone from another project made a note on the variant? Not sure about these things; we should probably ask users. These questions apply to all other Note items, so definitely worth getting right, as they may have data model implications as well.
- That one cannot do anything about a TechnicalReview saved-to-project that shows up in a different case seems to me a severe flaw. Forcing users to find the case with the VariantSample for which the TechnicalReview was saved in order to make changes does not seem like a feasible approach. Are we sure we want to allow saving-to-project now when it has such drawbacks and may become essentially impossible for users to undo?
- Mentioned via slack, but there was a color change issue where "present" calls showed a green checkmark upon selection but then a yellow checkmark upon refreshing.
- I doubt much can be done about this, but if I refresh shortly after making a selection, I lose the "*" denoting something is still processing, making it look as though either I didn't make a selection or my selection choice didn't change. 
- For the saved-to-project route, it's not clear to new users that one must write the note prior to making the selection, though I imagine they'll figure it out by experiment.
- The note item goes red when saving regardless of the call selection, which seems out of sync with the color coding of the call selection. Perhaps a different, unused color, or just the asterisk?
- Once a review is saved-to-project, selecting a new call (say "present") removes the saved-to-project note, which isn't intuitive to me. Shouldn't I have to click the saved-to-project classification again in order to remove it?

2022-06-30 18:28 UTC, alexkb0009 commented
@drio18 Edited your comment's list to be numbered so can refer to points below -->

1. Am trying to look into now but might need help replicating -- can you or @Bianca-Morris tell me steps you took to get there? So far it seems (on my local) any TechnicalReviews made from 1 project aren't visible at all to member of different project (e.g. Joel) nor can he edit them. The exception is admins. It might be my local (slightly updated) so will redeploy soon.
2. I think it's not that huge an issue but am unsure. This is still like a 'draft 1' for which we can gather feedback for -- if we add a rev_link from NoteTechnicalReview to VariantSample then it should be easy to unset the saved to project note from whichever Case -- we just need to understand what the UX for that could/should look like (i.e. when is it allowed).
3. Fixed (not yet deployed)
4. Yeah not much we can really do about this in a way that would be very stable -- there's always a delay between item being saved and it being indexed to search results. We could maybe cache 'recently saved data' into localStorage so that state would persist between refreshes, but this might degrade performance a little and be harder to manage (type of thing that would need to write 'upgrader' for if localStorage data model changes) -- but can explore that..
5. ?? You don't need to write note text before making selection, how did you come to find this? Should be able to save those independently...
6. Hm true.. will think about it a little. (The note becomes red to indicate that note_text is older than classification -- I probably need to expand this a little so is also red (or whatever indicator) when looking at saved note_text date vs saved call/classification date)
7. Yeah that makes sense to me, and probably would simplify UI code a little.

2022-06-30 19:46 UTC, alexkb0009 commented on src/encoded/schemas/structural_variant_sample.json
> +        "technical_review": {
Marking as resolved, data model has diverged a lot since this comment (no longer a complexy sub-object) and is just linkTo NoteTechnicalReview now (probably too simple to warrant a mixin).

2022-06-30 19:47 UTC, alexkb0009 commented on src/encoded/schemas/structural_variant_sample.json
> +                    "description": "True if call, false if no call, or undefined"
Outdated/resolved.

2022-06-30 19:48 UTC, alexkb0009 commented on src/encoded/static/components/item-pages/CaseView/TechnicalReviewColumn.js
> +    const handleOpenDropdownCall = useCallback(function handleOpenDropdownCall(){
Outdated/resolved (no longer a functional component)

2022-06-30 19:52 UTC, alexkb0009 commented on src/encoded/static/components/item-pages/CaseView/TechnicalReviewColumn.js
> +    const handleOpenDropdownCall = useCallback(function handleOpenDropdownCall(){
Currently we unset 'recently saved' technical review state (per VariantSample) when receive a new VariantSample from /search/ results which has an indexed/embedded 'technical_review.last_modifed.date_modified' which is more recent or equal to the 'recently saved' last_modifed.date_modified. In future we hopefully will integrate server-sent-events or websockets with a PubSub backend service and notify UI that things have reindexed without user having to manually search again on UI. And then figure out strategy to maybe update search-result-in-UI-memory (i.e. an array item inside SearchView state.results) to avoid having to refresh all search results (and make user lose context of where they've scrolled to).

2022-06-30 19:53 UTC, alexkb0009 commented on src/encoded/schemas/structural_variant_sample.json
> +                    "title": "Initial Call Made Date"
Addressed - was b.c. we need to remap schemas on deployments.

2022-06-30 20:05 UTC, alexkb0009 commented
TODO/Reminder for self - Adjust AJAX PATCH process to unsave from project before unsetting value - otherwise if fails for some unexpected reason (permissions, ...) then won't be stuck in an unhandled state ('nothing' saved to project).

2022-07-05 20:54 UTC, Bianca-Morris commented
Started looking at some of these... I'm going to report back if I can replicate #1 tomorrow. As for this...

>     5. ?? You don't need to write note text before making selection, how did you come to find this? Should be able to save those independently...

I'm having the same issue. Once you select "No Call > Recurrant Artifact"'s project-wide classification, you're no longer able to edit the note for whatever reason. And this is as the same user both times, with admin privileges.

[![Image from Gyazo](https://i.gyazo.com/ad975a323bb59f77ea57b8e3a007db1f.gif)](https://gyazo.com/ad975a323bb59f77ea57b8e3a007db1f)

2022-07-06 21:58 UTC, alexkb0009 commented on src/encoded/types/note.py
> +            return "(" + ("" if call == True else "No ") + "Call) " + classification
All set, will push soon

2022-07-06 22:06 UTC, alexkb0009 commented on src/encoded/types/variant.py
>          raise HTTPServerError("Couldn't update Item " + item_atid)
But yeah am not happy that have to have to that IF clause. Maybe can refactor so that check that response status code begins with 2XX or something... It'd fail for like /search/ requests that have 0 results (returns 404 I think) so might not be re-usable everywhere, but fine for our purposes here.

2022-07-06 22:07 UTC, alexkb0009 commented on src/encoded/types/variant.py
> +def process_items_process(context, request):
I renamed to "update-project-notes" .. explicit as to what it does now.

2022-07-06 22:08 UTC, alexkb0009 commented on src/encoded/types/variant.py
> +    li = {} # 'loaded notes'
Will push soon

2022-07-06 22:11 UTC, alexkb0009 commented on src/encoded/types/variant.py
> +        variant_fields_needed.append("technical_reviews.project")
Let me know if have idea(s) how to refactor... note how in some cases we want gene fields and in other cases we want variant fields, and in one case want both...

2022-07-06 22:12 UTC, alexkb0009 commented on src/encoded/types/variant.py
> +        add_or_replace_note_for_project_on_variant_or_gene_item("technical_review", variant, variant_patch_payload, remove=True)
Each note has its own specific fields/items. Like for discovery_intepretation we need to update both Gene and Variant, but in another case we want to just update Gene, and in other cases just Variant. If have a way to codify this better, please let me know.

2022-07-12 23:14 UTC, merged