Expanded File Submission
dbmi-bgm/cgap-portal pull request #616
Opened 2022-07-06 13:53 UTC by drio18

This PR refactors our file submission process to accommodate more file types.

The main changes include:

- A new item type, FileSubmitted, to be used for all submitted files (deprecating but not removing the FileFastq type)
- FileFormat metadata dictates whether such files are accepted (via the `valid_item_types` property)
- One property (`files`) on Sample and SampleProcessing to hold all submitted files (deprecating and removing `cram_files` on Sample with upgrader to move existing CRAMs there to `files`)
- A new class (`SubmittedFilesParser`) within `submit.py` to validate/create FileSubmitted items during submission
- Support for "extra files" associated with a File. We may not end up needing these after initially hearing they would be required, but the functionality should be entirely contained here. Some aspects of how "extra files" work are a little clunky with respect to uploads and PATCHes and may need further refactoring should we require extra files from users.

With these updates, the only required validation on submitted files is to check whether the extensions match accepted FileFormats, plus some additional checks on FASTQs to ensure accurate paired-end identification and pair matching.

2022-07-06 19:06 UTC, willronchetti approved these changes
Looks great, very nicely tested as well. Just some minor comments, and in need of a version bump.

2022-07-29 17:58 UTC, vstevensf reviewed
Clean code! Added some stylistic comments, mostly. Finishing this review but not "approving" because I still need to do integrated tests, if all goes well after that I will approve -- just wanted to get you these comments while I work on that.

2022-07-29 17:58 UTC, vstevensf commented on src/encoded/schemas/file_submitted.json
> +        "file_format",
noticed that for other schemas, file_format was just identifyingProperty instead of required. May be a nuance I don't understand, but is there a reason for this?

2022-07-29 17:58 UTC, vstevensf commented on src/encoded/tests/conftest_settings.py
> +    'access_key', 'disorder', 'document', 'file_fastq', "file_submitted",
single vs double quotes, just a stylistic choice

2022-07-29 17:58 UTC, vstevensf commented on src/encoded/submit.py
> +    'individual', 'sample_processing', 'families', 'family', 'files', "related_files",
quotation mark consistency (single vs double)

2022-07-29 17:58 UTC, vstevensf commented on src/encoded/submit.py
>      """converts cell contents to list, splitting by commas"""
it's pretty clear, but if you want to be even more explicit, I'd mention that the cell contents are strings (I think this is always the case?)

2022-07-29 17:58 UTC, vstevensf commented on src/encoded/submit.py
>      """converts cell contents to list, splitting by commas"""
edge case is when cell content is None, but you cover that in your code

2022-07-29 17:58 UTC, vstevensf commented on src/encoded/submit.py
> +        "GRCh37": ["37", "grch37"],
why is hg38 accepted but not hg37?

2022-07-29 17:58 UTC, vstevensf commented on src/encoded/submit.py
> +    ):
would add short documentation of what these parameters are, and their types

2022-07-29 17:58 UTC, vstevensf commented on src/encoded/submit.py
> +                    i + 1 + self.counter,
adding to this, you could change the initial value of self.counter to 1 instead of 0. But it does the same thing and I think it is clearer to include the 1 here for the header row

2022-07-29 17:58 UTC, vstevensf commented on src/encoded/submit.py
> +        """Remove suffix from file name.
may have missed it somewhere else in the code, but is there any check for the file name being in the correct format (for example, just including one period, to remove the suffix correctly)?

2022-08-05 12:50 UTC, vstevensf approved these changes
All done w integrated tests, seems to be functioning correctly!

2022-08-05 13:31 UTC, vstevensf requested changes

2022-08-05 13:31 UTC, vstevensf commented on src/encoded/tests/test_submit.py
> +VCF_EXTRA_FILE_1 = "foo_bar.vcf.gz.tbi"
there was an issue with this extra file in manual integrated tests

2022-08-05 13:41 UTC, vstevensf commented on src/encoded/tests/test_submit.py
> +VCF_EXTRA_FILE_1 = "foo_bar.vcf.gz.tbi"
^update, just include more explicit details about extra files in documentation

2022-08-05 13:42 UTC, vstevensf approved these changes

2022-08-15 16:27 UTC, drio18 commented on docs/public/help/accessioning_2.md
> + Do not pluralize the units.
We don't accept abbreviations at the moment, but perhaps we should. I'll add it to an existing ticket with suggested submit updates.

2022-08-15 16:27 UTC, drio18 commented on docs/public/help/accessioning_2.md
> +- Recommended options include: **peripheral blood**, **cord blood**,
Yup, I believe any string is accepted.

2022-08-15 16:27 UTC, drio18 commented on docs/public/help/accessioning_2.md
>  **Specimen ID**\*: An ID for the specimen that was collected for
It should be unique to the sample, yes. I think this is one of those fields we can make optional though.

2022-08-15 16:27 UTC, drio18 commented on src/encoded/submit.py
> +        "GRCh37": ["37", "grch37"],
For complicated historical reasons, I don't believe hg37 is ever used, while hg19 and GRCh37 are essentially interchangeable (and almost always used as such when discussing genome builds).

2022-08-15 22:07 UTC, merged