VS: row tracking
dbmi-bgm/cgap-portal pull request #622
Opened 2022-07-19 16:51 UTC by vstevensf

Solving the row tracking issue in SpreadsheetProcessing class within src/encoded/submit.py, which is used when processing spreadsheets for accession submissions (cases) and pedigree submissions (family histories). The largest change was refactoring the contents of self attribute "rows", which was originally a list of dictionaries, where each dictionary contained the row's contents from the spreadsheet. The dictionaries were left untouched, but rather than keeping rows as a list of those dictionaries, it was changed into a list of tuples (dict, int), where the dict was that row's data, just as before, and the integer was that row's line number within the spreadsheet (counted using enumeration and a preheader rows counter, for rows before the header in the submitted spreadsheet). Because of this change, there were some extraneous counter variables removed from other classes, specifically PedigreeMetadata and AccessionMetadata.

Two pytests were added to the corresponding test file to show correction of this error, and documentation was added to several classes within the submit.py file.

2022-07-19 17:14 UTC, vstevensf commented
[pedigree_test_example_error_row_count.xlsx](https://github.com/dbmi-bgm/cgap-portal/files/9143262/pedigree_test_example_error_row_count.xlsx)
[Case1_no-files.xlsx](https://github.com/dbmi-bgm/cgap-portal/files/9143266/Case1_no-files.xlsx)
Above are two test files that can be used for manual testing in local deployment. Use pedigree_test_example_error_row_count for Family History submissions, and Case1_no-files for Case submissions.

2022-07-19 20:31 UTC, drio18 reviewed
Dropping some comments but still need to test the functionality myself. Overall, looks great; a very clean first PR, and the added documentation is appreciated. Most of my comments are style related and therefore optional, though I'd encourage many of them since you're still new to the codebase. You'll develop your own style as you go, but comments regarding DRY, helper functions, being explicit, etc. are ones I wish more people had encouraged me to use early on as they do make development easier in the long run.

Also, there are some formatting errors I would have expected your linter to pick up on. However, you can go ahead and reformat both `submit.py` and `test_submit.py` here with `black`. This is one style thing I want to enforce for our code since it makes it much more readable and consistent. If you don't have it installed, `pip install black` into your virtualenv and then run `black src/encoded/submit.py` and similarly to reformat.

2022-07-19 20:31 UTC, drio18 commented on src/encoded/tests/test_submit.py
> +    ])
Since you're re-using many of the same rows here, set the rows as constants and then re-use them as needed, either in new constants or in the parametrize call:
```suggestion

BLANK_ROW = ["", "", ...]
HEADER_ROW = ["Unique Analysis ID*", ...]
....
ROWS_WITH_ERROR_IN_ROWS_2_4 = [BLANK_ROW, HEADER_ROW, ...]
@pytest.mark.parametrize('digested_xlsx, expected_error_row_number_1, expected_error_row_number_2', [
        (ROWS_WITH_ERROR_IN_ROWS_2_4, "Row 2", "Row 4"),
        ...
```

2022-07-19 20:31 UTC, drio18 commented on src/encoded/tests/test_submit.py
> +    assert success
Consider re-factoring to not having 2 expected row numbers, as well as including a parametrize call that has no errors. Reasons for this are twofold:

- You should catch different types of errors in separate parametrize calls (and probably document which error exists for which call with a quick comment to make it more obvious). You can then generate another call to mix different errors together if you feel it's necessary.
- Requiring 2 errors for parametrize call is arbitrary and forces the next person refactoring to either refactor the test or include 2 errors when they may want to have 1 (or 3)

Also, the comment is not adding much here.
```suggestion
def test_xls_to_json_accession_row_counting(testapp, project, institution, digested_xlsx, expected_error_rows):
    rows = (row for row in digested_xlsx)
    json_out, success = xls_to_json(testapp, rows, project, institution, TEST_INGESTION_ID1, 'accessioning')
    joined_errors = "".join(json_out["errors"])
    for row_with_error in expected_error_rows:
         assert f"Row {row_with_error}" in joined_errors
    assert success
```

2022-07-19 20:31 UTC, drio18 commented on src/encoded/tests/test_submit.py
> +def test_xls_to_json_accession_row_counting(testapp, project, institution, digested_xlsx, expected_error_row_number_1, expected_error_row_number_2):
Feel free to add docstrings to tests to explain explicitly what errors it's accounting for; in this case, what counting errors should be caught?

2022-07-19 20:31 UTC, drio18 commented on src/encoded/tests/test_submit.py
> +    assert success
Similar to above regarding row constants in the calls, etc.

2022-07-20 19:15 UTC, drio18 requested changes
Tested the functionality on my local for both cases and pedigrees; worked like a charm.

From my previous batch of comments, please do re-format the files with `black`, fix some of the smaller formatting errors that aren't picked up by `black` (such as within docstrings), refactor the test parametrization calls to use constants that can be re-used more easily, and refactor the expected row errors a bit as suggested. The rest is optional based on whether you agree with the suggestion or not.

Once you think it's good to merge, please request a re-review from me, and I'll give it a once over before approving.

2022-07-22 06:37 UTC, vstevensf commented on src/encoded/tests/test_submit.py
> +                ({k: v for k, v in example_rows[0][0].items()}, 0),
in this case, I did not because although I access from this list of tuples several times, different cases access from different indices, as well as certain data items (from within the tuple, for instance). Since there are so many variations, creating a helper function was approx as complicated as hardcoded accessing.

2022-07-22 19:45 UTC, drio18 approved these changes

2022-07-22 19:45 UTC, drio18 commented on src/encoded/tests/test_submit.py
> +]
Consider moving to the top of the module where the other constants live. It's a little less convenient when modifying them for tests, but it helps to know where everything lives, and our general style has been to keep constants between imports and functions.

2022-07-22 19:45 UTC, drio18 commented on src/encoded/tests/test_submit.py
> +]
Similar to above.

2022-07-27 17:20 UTC, merged