Vs cypress test inserts
dbmi-bgm/cgap-portal pull request #633
Opened 2022-08-25 23:58 UTC by vstevensf

The inserts themselves are in the folder src/encoded/tests/data/cypress-test-inserts -- here are some notes:
- new projects: Cypress Main and Cypress Personas
- new institutions: Cypress Main DBMI and Cypress Personas Institution
- new users: a director (admin), clinician, developer, and scientist for both new projects/institutions
- I updated the project and institution to Cypress Main for all inserts except variants, structural variants, genes, and fileformat, whose proj/inst is still CGAP Core
- I also updated all aliases to refer to cypress-main, not cgap-core. Relevant inserts for this: case, family, file_fastq, individual, report, sample_processing, and sample
- I added two new cases, based on the cases NA12879-WGS-Trio and HG002 from Wolf. I pulled 50 variant samples and 50 structural variant samples from NA12879, and 25 variant and structural variant samples from HG002. For overlap, I updated 20/25 variant & structural variant samples from HG002 to have the same (structural) variants as case NA12879. With this update, I also updated the annotation_id based on the updated (structural) variant.
- variant samples showing up in the filter space for both cases. There were extra processed files that I deleted, as well as downstream QC files, so the loading is much quicker too. Pretty barebones -- no gene lists, cohorts, etc., just the two samples and their (structural) variant samples.

To deploy locally (new cypress inserts + master inserts), I created a new load function within src/encoded/loadxl.py  called `load_cypress_data` -- in development.ini , switch line 25 to `load_test_data = encoded.loadxl:load_cypress_data`  to invoke this load function

2022-08-30 15:47 UTC, drio18 requested changes
Overall, inserts look complete and ready for actual cypress tests. The Files and QualityMetrics can be cut down a lot, and I'd highly recommend doing so. Other strong recommendations not appearing elsewhere include:

- Updating docs to explain the use for these inserts
- Adding your scripts to the repo that were helpful when managing these inserts so they're available to future developers

A weaker recommendation is to consider gzipping the larger insert files, say those over ~1 Mb, to reduce file storage since the diffs can't be displayed within github anyway.

2022-08-30 15:47 UTC, drio18 commented on pyproject.toml
> +version = "10.2.1"
A new feature like this deserves a minor version bump rather than a patch bump (used for bug fixes).

2022-08-30 15:47 UTC, drio18 commented on src/encoded/loadxl.py
> +    overwriting duplicate items in both directories, to match cypress-test-inserts
I don't believe you're overwriting, which is desirable here. The docstring should reflect that you're not overwriting by default though.

2022-08-30 15:47 UTC, drio18 commented on src/encoded/tests/data/cypress-test-inserts/sample_processing.json
> +            "854e2046-5329-4550-8671-578bd106a291"
We should only need ~4 of these VCFs, I believe. The remainder should be removed from the inserts, and all of their associated QualityMetrics should also be removed.

2022-08-30 15:47 UTC, drio18 commented on src/encoded/tests/data/cypress-test-inserts/sample_processing.json
> +        ],
As above, this list should be cut down significantly and associated QualityMetrics removed.

2022-08-30 17:56 UTC, Bianca-Morris reviewed
Took a look; mostly looks good to me. I have a couple of wish list items, though:

2022-08-30 17:56 UTC, Bianca-Morris commented on src/encoded/tests/data/cypress-test-inserts/quality_metric_bamqc.json
> +    {
Would it be possible for you to add some bamchecks to go with some of these? When we built the front-end for the bioinfo tables, [we were running under the assumption that Bamqc would only be present if there's also a bamcheck](https://github.com/dbmi-bgm/cgap-portal/blob/7456c90bb8394afde8b14e9ff24a4a84243ebe51/src/encoded/static/components/item-pages/CaseView/index.js#L816) (a limitation Soo had made at the time). I'm not sure if this is still the case (maybe @drio18 or @B3rse would know), but that would be helpful for testing that part of the interface as it currently stands.

2022-08-30 17:56 UTC, Bianca-Morris commented on src/encoded/tests/data/cypress-test-inserts/structural_variant_sample.json
> +[
Might also be good to have a couple of BIC-Seq2 examples so we can test that part of the interface on the SV annotation space. And if it's possible that there could be multiple callers (e.g. Manta AND BIC-Seq), some examples of those would be nice, as well.

2022-08-30 17:56 UTC, Bianca-Morris commented on src/encoded/tests/data/cypress-test-inserts/sample_processing.json
> +            "854e2046-5329-4550-8671-578bd106a291"
Agree with Doug; I was just thinking that there were a lot of these...

2022-08-30 18:08 UTC, drio18 commented on src/encoded/tests/data/cypress-test-inserts/quality_metric_bamqc.json
> +    {
This assumption no longer holds for our current pipelines, which is why newer cases lack BAM coverage QC information. I wouldn't worry too much about this here because all this QC information will be moving to calcprops in the near future.

2022-08-30 18:39 UTC, Bianca-Morris commented on src/encoded/tests/data/cypress-test-inserts/quality_metric_bamqc.json
> +    {
Ok, do you think it would be worth putting together a fix for some of that code at some point soon, or would it be better to wait until the new calcprops are ready?

2022-08-30 19:00 UTC, drio18 commented on src/encoded/tests/data/cypress-test-inserts/quality_metric_bamqc.json
> +    {
It can probably wait. I'm working to wrap up minor refactoring and adding tests now in the hopes of passing off to you tomorrow.

2022-10-04 01:20 UTC, vstevensf commented on src/encoded/tests/data/cypress-test-inserts/structural_variant_sample.json
> +[
Added to case HG002 :)

2022-10-05 17:31 UTC, drio18 reviewed
I'd still recommend gzipping some of the larger insert files to save some repo space, but otherwise I think this is good to go as a first cut. One final test that may be useful prior to merging is to attempt to POST/PATCH all of these items to devtest for validation only to ensure there are no conflicts with existing items or with current schema. Since everything here is self-contained though, things can always be fixed on the fly without much worry, so your choice on the matter.

I'll formally approve once the scripts are included so I don't forget to take a look at them.

2022-10-13 18:38 UTC, drio18 approved these changes
Nothing blocking, but see the comment on versioning. Inserts themselves should have everything required for a majority of tests can can be iterated on from here.

2022-10-13 18:38 UTC, drio18 commented on pyproject.toml
> +version = "11.1.2"
Here and in the changelog, you'll want to bump to `11.1.0` rather than `11.1.2`. With semantic versioning, "higher-level" increases imply "lower level" numbers reset to 0.

2022-10-13 18:38 UTC, drio18 commented on src/encoded/tests/data/README.md
> +This set of inserts does not include Note or FilterSet items, since these will be created by the tests through interaction with the UI.
Consider deleting these lines as they're specific to the current state of affairs but may become outdated shortly, requiring updates to these docs or more likely leaving these docs outdated.

2022-10-14 14:12 UTC, Bianca-Morris approved these changes
See the comment I left on Doug's comment. (Also, make sure you update the `CHANGELOG.rst`file too; as the incorrect version # is in that, as well)

2022-10-17 16:59 UTC, merged