Case QC Results
dbmi-bgm/cgap-portal pull request #662
Opened 2022-10-26 20:33 UTC by drio18

Here, we create new calculated properties on SampleProcessing and Case items to expand the functionality of the QC table (adding additional flags, QC metrics for all Samples) and enable filtering of Cases by overall QC status.

The primary changes include:

- New calcprop on SampleProcessing that makes use of new class dedicated to QC parsing
- New calcprop on Case that uses new calcprop on SampleProcessing
- Updated inserts for front-end to use for new QC table creation

I decided to separate out the work over two calcprops instead of one giant one on Case items since gathering the requirements of the QC table is a big process and ideally does not occur frequently. I reasoned SampleProcessings are likely updated/re-indexed less frequently than Cases, and the updates on SampleProcessings are usually related to things that directly impact the QC metrics.

2022-10-27 18:02 UTC, willronchetti reviewed
Lots of good stuff here, but I think there are some things worth revising prior to merge if we have the time

2022-10-27 18:02 UTC, willronchetti commented on src/encoded/tests/test_types_sample.py
> +            ("1X", {"workup_type": "foo"}, "pass"),
Should an effectively unknown workup type pass the coverage check unconditionally (as this suggests)?

2022-10-27 19:15 UTC, Bianca-Morris commented on src/encoded/types/case.py
> +                },
I just checked with Shannon to see if there was any need for this level of detail. If it is possible to do this easily, it would be nice to have, so we can display it as a popover when one clicks on the Flag from the QC column. If it's complicated to do, we can try to include something like it in a later version. But it looks like Dana will want to have an "overview" listing of all of the flags for each family member in the QC column on the home page at some point.

Also, I actually don't know that we need the overall flag, now that I'm looking at this. The home dashboard will just have the numbers of warns and fails listed, so the overall one doesn't seem necessary, since they won't be collapsed.

2022-10-27 19:51 UTC, Bianca-Morris reviewed
This should mostly work for what I need. Had a few comments/questions, though.

2022-10-27 19:51 UTC, Bianca-Morris commented on src/encoded/schemas/case.json
>      "columns": {
I'm adding the following column here (before the Report column): 
```
     "quality_control_flags.flag": {
            "title": "QC",
            "sort_fields": [
                {
                    "field": "quality_control_flags.flag",
                    "title": "Overall QC Status"
                },
                {
                    "field": "quality_control_flags.warn",
                    "title": "Number of QCs with Warnings"
                },
                {
                    "field": "quality_control_flags.fail",
                    "title": "Number of Failed QCs"
                }
            ]
        },
```
It probably makes sense for me to do it in my branch, since there's not going to be a great looking column display for that until I add the UI on my end. But if you see any issues with that, let me know.

2022-10-27 19:51 UTC, Bianca-Morris commented on src/encoded/tests/data/inserts/case.json
> +    }
Noticing that I'm still getting that "[No Family Linked to This Case](https://gyazo.com/a6443e8258bb2ff4f5294de0e2738a4a)" UI message for the 01234 case, even though it has the "Bluethumb Family" linked in the SampleProcessing. I think the last time that happened, it was because the wrong family was linked? Can you double check that?

2022-10-27 20:17 UTC, drio18 reviewed
Responding to some comments before starting to refactor. Agree the class is bulky and naming/docstrings can be improved; will get to it shortly.

2022-10-27 20:17 UTC, drio18 commented on src/encoded/types/sample.py
> +        return result
They're not, but I prefer them as a means to easily see values when debugging.

2022-10-27 20:17 UTC, drio18 commented on src/encoded/types/sample.py
> +        return result
Much cleaner; never came to mind.

2022-10-27 20:17 UTC, drio18 commented on src/encoded/types/sample.py
> +        if coverage is not None:
Good catch; that's a remnant from a previous implementation. Any exceptions in the evaluator functions will be caught and logged elsewhere.

2022-10-27 20:20 UTC, drio18 commented on src/encoded/schemas/case.json
>      "columns": {
Yup, sounds good.

2022-10-27 20:43 UTC, drio18 commented on src/encoded/tests/data/inserts/case.json
> +    }
Whoops, should be all set now.

2022-10-27 20:48 UTC, willronchetti commented on src/encoded/tests/test_types_sample.py
> +            (PROCESSED_FILES_2, 3, True),
Since they aren't integrated tests though the effect on test time should be minimal/nonexistent so it's fine to keep them if you want

2022-10-27 22:37 UTC, vstevensf commented on src/encoded/types/sample.py
> +        """Gather and process all data to make calcprop.
Also list what data is needed to make the calcprop

2022-10-27 23:00 UTC, vstevensf commented on src/encoded/types/sample.py
> +            file_vcf_to_ingest = file_item.get(self.VCF_TO_INGEST, False)
By definition, will a processed file of file_type = "full-annotated vcf" (instead of "full annotated vcf", which is FINAL_VCF_FILE_TYPE) _always_ have `"vcf_to_ingest" = True` ? Just wanted to double check this, I'm sure there's other code that you are more familiar with that covers this :)

2022-10-27 23:08 UTC, vstevensf commented on src/encoded/types/sample.py
> +                and self.VEP_ANNOTATED_STRING in file_type.lower()  # Pretty fragile
Why is this fragile? Because a vep-annotated VCF can be "vep annotated" instead of "vep-annotated" (I didn't think so, but asking just in case)? Or because of possible future changes to schema?

2022-10-27 23:10 UTC, vstevensf commented on src/encoded/types/sample.py
> +        """Collect processed files of interest from a SampleProcessing.
Add more detail to this docstring, if possible -- mentioning that you search through the processed files in reversed chronological order, and returns True is either SV, SNV, or vep-annotated VCF is found (rather than just saying this in the `:return` value below)

2022-10-27 23:12 UTC, vstevensf commented on src/encoded/types/sample.py
> +        """Collect processed files of interest from a SampleProcessing.
And that you add them and QC metadata to the `processed_files_with_quality_metrics` list, if found. Could be overkill since the helper function called does this, up to you

2022-10-27 23:14 UTC, vstevensf commented on src/encoded/types/sample.py
> +            (file_item, properties_to_find, property_replacements)
I agree with this, but also don't mind them being listed out either

2022-10-28 02:59 UTC, vstevensf commented on src/encoded/types/sample.py
> +        another if exists in original.
And also specify that the properties are keys within a dict, even if it is described in the `:param` values

2022-10-28 03:02 UTC, vstevensf commented on src/encoded/types/sample.py
> +        another (if exists) in formatting expected of calc prop.
^ highly agree w this

2022-10-28 03:58 UTC, vstevensf commented on src/encoded/types/sample.py
> +            processed_file,
Good place where a data class would be useful, as per Will's suggestion

2022-10-28 04:00 UTC, vstevensf commented on src/encoded/types/sample.py
> +            if flagged_properties is not None:
could just be `if flagged_properties`, but this works too because more explicit

2022-10-28 04:12 UTC, vstevensf commented on src/encoded/tests/test_types_case.py
> +    proband_title = 'proband_boy WGS-Group'
good renaming

2022-10-28 04:12 UTC, vstevensf requested changes
Check comments for suggestions, and overall agree with Will's comments as well

2022-10-31 21:29 UTC, dvuzman reviewed
The flags look good. Please don't implement the de-novo flag for now and consider changing the "warn" ranges for the WES and WGS coverages. More details could be found in my specific comments.

2022-10-31 21:29 UTC, dvuzman commented on src/encoded/types/sample.py
> +                warn_limit = 60
Would you consider elevating the "warn" limit to "25" in WGS and "70" in WES?

2022-10-31 21:29 UTC, dvuzman commented on src/encoded/types/sample.py
> +        :type predicted_sex: str
I noticed during Bianca's demo of the QC tab today, that the predicted sex was "male" and not "M". Would be important to accommodate for such scenarios in case such output is possible (although based on the output on other accounts, I assume that it is not possible since I see only F/M as the "Predicted Sex" on the portal and "female"/"male" on the peddy report).

2022-10-31 21:29 UTC, dvuzman commented on src/encoded/types/sample.py
> +        upper_limit = 5
Doug, the upper limit for de-novo fraction should be 0.5% and not 5%. However, most values are higher than that and the calculation will need to change based on today's conversation on how the de-novo fraction is calculated (using GATK for SNVs only and not novoCaller for SNV&indels). Please keep the flag and its upper value as comments for now, and I will confirm this flag after discussing with Michele et al at the Bioinformatics meeting and confirming next steps.

2022-11-02 17:14 UTC, Bianca-Morris commented on src/encoded/types/sample.py
> +        :type predicted_sex: str
I can fix this in the UI if it's too difficult; I think I was doing that on my end in the previous version, but removed some of that code in the re-work.

2022-12-12 19:07 UTC, willronchetti approved these changes
Generally looks great!

2022-12-14 17:34 UTC, vstevensf commented on src/encoded/tests/utils.py
> +import re
nice refactoring of this function into new file

2022-12-14 18:10 UTC, vstevensf commented on src/encoded/tests/utils.py
> +import re
would recommend adding a small comment snippet explaining how and where this is used only within the tests

2022-12-14 18:23 UTC, vstevensf commented on src/encoded/tests/data/workbook-inserts/case.json
>  [
Would recommend updating the documentation for workbook-inserts in`/src/encoded/tests/data/README.md`, since it looks like you are invoking these inserts within the tests with `@pytest.mark.workbook` rather than importing anywhere with `from .workbook_fixtures import workbook`

2022-12-14 18:51 UTC, drio18 commented on src/encoded/tests/data/workbook-inserts/case.json
>  [
The `pytest.mark.workbook` is done to mark tests, essentially labeling them as belonging to a certain group. They can then be selectively included in the tests run when invoking pytest; more documentation [here](https://docs.pytest.org/en/7.2.x/example/markers.html#mark-run). The workbook inserts are loaded by calling the `workbook` pytest fixture, found [here](https://github.com/dbmi-bgm/cgap-portal/blob/master/src/encoded/tests/conftest.py#L403-L407).

I'll update that documentation though as it is no longer accurate.

2022-12-14 19:01 UTC, vstevensf approved these changes
looks ready to go :) don't forget to merge master and version

2022-12-15 18:07 UTC, merged