Add notes for Case items
dbmi-bgm/cgap-portal pull request #737
Opened 2023-07-27 19:15 UTC by crfmc

Corresponds to [Trello Ticket](https://trello.com/c/dyNdiNDr/724-add-comments-on-cases)

2023-09-29 15:42 UTC, Bianca-Morris requested changes
Nice job on this! Most of the comments on here are smaller nitpicks and things that probably don't need to be explicitly addressed before merging, but there are some things in `CaseNotesColumn` that I'd like changed before approval. It should be fairly clear which is which, but if it isn't, please don't hesitate to ask!

2023-09-29 15:42 UTC, Bianca-Morris commented on src/encoded/static/components/browse/CaseNotesColumn.js
> +  },[currentText, lastSavedText.text]);
I see what you're trying to do here (and I see how it has the added benefit of getting the note indicator in the display title column working), however, I would seriously caution against doing this kind of DOM manipulation via vanilla JS APIs inside of React code. This is typically considered against best practice for a variety of reasons:

- React manages the DOM, and if you manually modify it, React might not be aware of those changes, which can lead to inconsistencies and unexpected behavior.
- In a similar vein, React optimizes rendering by batching updates and making the fewest possible changes to the DOM -- if you manually edit it with vanilla JS, that can create performance issues.
- And finally, it makes the code much harder to understand and maintain because it's outside expected structure of React applications. If we do things like this in enough places it will become very difficult to track down and debug issues because suddenly there are two different development philosophies at work.

I know we have some instances in our code-base where we do use some vanilla DOM APIs... Alex B. used to use them occasionally for cleaning up event handlers for global events, grabbing window size for resizing methods, and integrating with packages (sometimes HiGlass falls into this category); there was usually quite a bit of back-and-forth on whether we should do it and if so, why. We could probably be better about documenting these choices/their reasoning in comments moving forward, though.

Anyway, I think the main benefit of your approach here that cannot be easily achieved without vanilla APIs is the tiny UX detail of updating the note color in the display title column. I'm just not sure that's worth it.

So, that is the only thing I would say is a "must-fix" before merging this. If you lose the display title note reactivity, that's fine.

2023-09-29 15:42 UTC, Bianca-Morris commented on src/encoded/static/components/browse/CaseNotesColumn.js
> +      */
Most of this stuff is solid, I'd say the one main thing I'd change is to add some additional error handling to indicate to the user if/when an error has occurred and what action they should take.

This can probably be a short snippet added right beneath the other info text:
```
{error && <p className="text-danger">{errorMsg}</p>}
```

Shouldn't be too big; just have to create a piece of state somewhere to store the error state once it's created (prob can just be a boolean and then have a common error message: "An error has occurred. Please try again or contact an administrator." Drilling that error message to the appropriate place to render it might be the most annoying thing.

2023-09-29 15:42 UTC, Bianca-Morris commented on src/encoded/static/components/browse/CaseNotesColumn.js
> +                  warning: "Please allow the system a few minutes to reflect these changes."
I see this warning text repeated a few times, might be best to pull it out and make it a `const` that can be passed into all 3. 

Also, can you try changing the warning text to:
"It may take some time for changes to be fully reflected in search results, please refresh or search again in a few minutes."

It's a little longer, but I'm hoooping that'll be around two lines-ish? Not sure.

2023-10-02 18:50 UTC, drio18 approved these changes
One small comment to address; otherwise, tested well (no front-end code review from me). I found the lack of an explicit delete note button a little odd but figured out I could do it by saving with no text; can't remember what we do with technical review here.

2023-10-03 20:10 UTC, crfmc commented on src/encoded/static/scss/style.scss
> +        "encoded/modules/case-notes";
Moving styles into the "search" module

2023-10-03 20:13 UTC, crfmc commented on src/encoded/static/components/browse/columnExtensionMap.js
> +                 * attribute in the stylesheets (_case-notes.scss).
Removed

2023-10-03 20:14 UTC, crfmc commented on src/encoded/static/components/browse/columnExtensionMap.js
> +                 * to prevent intitial render. It is added on each render of
Removed

2023-10-03 20:15 UTC, crfmc commented on src/encoded/static/components/browse/CaseNotesColumn.js
> +  },[currentText, lastSavedText.text]);
Thank you for calling this out and explaining! Removed

2023-10-03 20:16 UTC, crfmc commented on src/encoded/static/components/browse/CaseNotesColumn.js
> +      {/* Render either empty string or note.note_text */}
Removed

2023-10-03 20:17 UTC, crfmc commented on src/encoded/static/components/browse/CaseNotesColumn.js
> +                  warning: "Please allow the system a few minutes to reflect these changes."
Created variables for warning and error messages. Thank you! Resolved.

2023-10-03 20:18 UTC, crfmc commented on src/encoded/static/components/browse/CaseNotesColumn.js
> +      */
Added. Fits on two lines as well. Thanks!

2023-10-11 14:14 UTC, crfmc commented on src/encoded/schemas/case.json
> +            ]
It seems to be working for me as well but I will check again once deployed to a test environement.

2023-10-11 14:15 UTC, crfmc commented on pyproject.toml
> +version = "14.3.2"
Fixed. Thank you!

2023-10-13 18:10 UTC, Bianca-Morris commented
> One small comment to address; otherwise, tested well (no front-end code review from me). I found the lack of an explicit delete note button a little odd but figured out I could do it by saving with no text; can't remember what we do with technical review here.

Hmm, yeah that's fair. Can bring that up for the future.

2023-10-13 18:13 UTC, Bianca-Morris approved these changes
Looks good to me! Thanks for making so many of the changes I suggested. Should be good to go for now; any additional feedback we can collect in another ticket and work on later.

2023-10-16 16:43 UTC, merged